package training.jpa;

// Generated Oct 30, 2015 4:33:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer id;
	private Employee employee;
	private Department department;
	private String firstName;
	private String lastName;
	private String phone;
	private Date startTime;
	private Date leaveTime;
	private byte level;
	private Set employees = new HashSet(0);

	public Employee() {
	}

	public Employee(Employee employee, Department department, String firstName,
			String lastName, String phone, Date startTim, byte level) {
		this.employee = employee;
		this.department = department;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phone = phone;
		this.startTime = startTim;
		this.level = level;
	}

	public Employee(Employee employee, Department department, String firstName,
			String lastName, String phone, Date startTim, Date leaveTime,
			byte level, Set employees) {
		this.employee = employee;
		this.department = department;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phone = phone;
		this.startTime = startTim;
		this.leaveTime = leaveTime;
		this.level = level;
		this.employees = employees;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTim) {
		this.startTime = startTim;
	}

	public Date getLeaveTime() {
		return this.leaveTime;
	}

	public void setLeaveTime(Date leaveTime) {
		this.leaveTime = leaveTime;
	}

	public byte getLevel() {
		return this.level;
	}

	public void setLevel(byte level) {
		this.level = level;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

}
